"""Build the shipped case corpus, with expected output generated by the engine.

Run from the repo root:

    python services/engine/scripts/sync_cases.py

The corpus is committed, not built at runtime, for three reasons: the web app can import it
into a Vercel bundle, `tests/test_golden.py` can prove it still matches the engine, and a
reviewer can read exactly what the tool produces on a real scenario without running anything.

Cases are authored here as Python literals because the tick arithmetic - anchors, drift,
budget windows - has to be derived, not typed. Hand-writing 4096 anchors in JSON would be a
way of introducing typos.
"""

from __future__ import annotations

import json
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any, NamedTuple

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT / "services" / "engine" / "src"))

from tickrate_sim import (  # noqa: E402 - path bootstrap must precede the import
    budget_profile,
    diff_tables,
    parse_table,
    parse_trace,
    replay,
    tickrate_stats,
    validate_table,
)

DATA = REPO_ROOT / "apps" / "web" / "data"

#: 64 Hz is 15.625 ms per tick.
MS_PER_TICK_64 = 1000.0 / 64.0


class AnchorRate(NamedTuple):
    """How a trace's wall-clock anchors are sampled.

    One stamp every `stride` ticks, at `ms_per_tick` milliseconds per tick. Both halves matter
    and neither can be inferred from the other: a stride of 64 ticks against a 58 Hz clock is
    a server that is nine percent slow, which is a different scenario from a different stride.
    """

    stride: int
    ms_per_tick: float = MS_PER_TICK_64


#: A server hitting its declared 64 Hz.
ON_RATE = AnchorRate(64)
#: A server provisioned for 64 Hz and delivering 58: 1000/58 ms per tick, sampled every 64 ticks.
DRIFTED = AnchorRate(64, 1000.0 / 58.0)

#: Either an anchor sampling rate, or explicit anchors.
Anchors = AnchorRate | list[dict[str, int]]


def state(name: str, *, terminal: bool = False, description: str = "") -> dict[str, Any]:
    return {"name": name, "terminal": terminal, "description": description}


def rule(
    rule_id: str,
    source: str,
    target: str,
    *,
    min_ticks: int = 0,
    max_ticks: int | None = None,
    repeatable: bool = True,
    guard: str = "",
) -> dict[str, Any]:
    return {
        "id": rule_id,
        "source": source,
        "target": target,
        "minTicks": min_ticks,
        "maxTicks": max_ticks,
        "repeatable": repeatable,
        "guard": guard,
    }


def anchors_for(ticks: Iterable[int], ms_per_tick: float = MS_PER_TICK_64) -> list[dict[str, int]]:
    """Millisecond stamps derived from tick numbers, so anchors cannot drift from the rate."""
    return [{"tick": tick, "ms": int(round(tick * ms_per_tick))} for tick in ticks]


# ------------------------------------------------------------------ tables

SKIRMISH_64 = {
    "id": "skirmish-64",
    "tickrateHz": 64,
    "entry": "lobby",
    "states": [
        state("lobby", description="waiting for players to ready up"),
        state("countdown", description="fixed pre-match countdown"),
        state("live", description="match running"),
        state("resimulating", description="rollback re-simulation"),
        state("paused", description="administrative pause"),
        state("ended", terminal=True, description="terminal"),
    ],
    "transitions": [
        rule("begin_countdown", "lobby", "countdown", max_ticks=180),
        rule("start_match", "countdown", "live", min_ticks=192, max_ticks=192),
        rule("begin_rollback", "live", "resimulating"),
        rule("finish_resim", "resimulating", "live", min_ticks=1, max_ticks=10),
        rule("pause_match", "live", "paused", repeatable=False),
        rule("resume_match", "paused", "live", min_ticks=30, max_ticks=9600),
        rule("end_match", "live", "ended", repeatable=False),
        rule("abandon_match", "lobby", "ended", repeatable=False),
    ],
}

# Revision 2 of the same table: the countdown is lengthened to 4 s and the host-abandon edge
# is dropped, because the host leaving mid-lobby was producing a `ended` state that no
# client had a transition rule for.
SKIRMISH_64_R2 = {
    **SKIRMISH_64,
    "id": "skirmish-64-r2",
    "transitions": [
        rule("begin_countdown", "lobby", "countdown", max_ticks=180),
        rule("start_match", "countdown", "live", min_ticks=256, max_ticks=320),
        rule("begin_rollback", "live", "resimulating"),
        rule("finish_resim", "resimulating", "live", min_ticks=1, max_ticks=10),
        rule("pause_match", "live", "paused", repeatable=False),
        rule("resume_match", "paused", "live", min_ticks=30, max_ticks=9600),
        rule("end_match", "live", "ended", repeatable=False),
    ],
}

# A table that is wrong in five different ways at once, to show what `validate_table` finds.
SKIRMISH_BROKEN = {
    "id": "skirmish-broken",
    "tickrateHz": 64,
    "entry": "warmup",
    "states": [
        state("staging"),
        state("staging", description="duplicate declaration"),
        state("playing"),
        state("orphaned", description="nothing can reach this"),
        state("finished", terminal=True),
        state("looping"),
    ],
    "transitions": [
        rule("to_playing", "staging", "playing"),
        rule("to_playing_again", "staging", "playing"),
        rule("inverted_budget", "playing", "looping", min_ticks=90, max_ticks=30),
        rule("negative_budget", "looping", "playing", min_ticks=-1),
        rule("into_the_void", "playing", "nowhere"),
        rule("out_of_the_end", "finished", "playing"),
    ],
}


# ------------------------------------------------------------------ traces


def trace(
    trace_id: str,
    events: list[tuple[int, str]],
    *,
    end_tick: int,
    rate: Anchors = ON_RATE,
) -> dict[str, Any]:
    """One shipped trace. `rate` is either a tick stride or explicit anchors.

    Anchors are derived from the rate rather than typed, so a change to the declared tickrate
    cannot leave stale millisecond values behind in the committed corpus.
    """
    return {
        "id": trace_id,
        "tableId": "skirmish-64",
        "startTick": 0,
        "endTick": end_tick,
        "events": [{"tick": tick, "target": target, "note": ""} for tick, target in events],
        "anchors": (
            anchors_for(range(0, end_tick + 1, rate.stride), rate.ms_per_tick)
            if isinstance(rate, AnchorRate)
            else rate
        ),
    }


def jitter_anchors(steps: int = 160) -> list[dict[str, int]]:
    """Alternating 50 ms / 75 ms frame gaps, on average exactly a 64 Hz budget.

    Anchors sit every 4 ticks, where 4 ticks of a 64 Hz server is 62.5 ms. The clock
    alternates +50 ms and +75 ms, and 50 + 75 = 125 ms for 8 ticks - so the *mean* rate is
    exactly 62.5 Hz per tick while no single 4-tick interval ever is (it reads 80 Hz, then
    53.3 Hz, then 80 Hz). This is the case that separates "the average looks fine" from "the
    server is healthy", and it is why the engine reports jitter alongside the mean rather
    than instead of it.
    """
    stamps: list[dict[str, int]] = [{"tick": 0, "ms": 0}]
    clock = 0
    for index in range(steps):
        clock += 50 if index % 2 == 0 else 75
        stamps.append({"tick": (index + 1) * 4, "ms": clock})
    return stamps


#: Sampling every 64 ticks gives one anchor per second of a 64 Hz match - dense enough for a
#: drift figure to mean something, sparse enough that a reviewer can read the JSON.
ONCE_PER_SECOND = list(range(0, 7681, 64))

CLEAN = trace(
    "clean-64hz",
    [
        (24, "countdown"),
        (216, "live"),
        (1200, "resimulating"),
        (1206, "live"),
        (4800, "ended"),
    ],
    end_tick=7680,
    rate=ON_RATE,
)

ROLLBACK_STORM = trace(
    "rollback-storm",
    [
        (24, "countdown"),
        (216, "live"),
        (300, "resimulating"),
        (331, "live"),
        (420, "resimulating"),
        (470, "live"),
        (600, "resimulating"),
        (688, "live"),
        (900, "ended"),
    ],
    end_tick=1920,
    rate=ON_RATE,
)

UNDECLARED_SKIP = trace(
    "undeclared-skip",
    [
        (24, "countdown"),
        (240, "ended"),
    ],
    end_tick=600,
    rate=ON_RATE,
)

COUNTDOWN_TOO_FAST = trace(
    "countdown-too-fast",
    [
        (24, "countdown"),
        (30, "live"),
        (900, "ended"),
    ],
    end_tick=1200,
    rate=ON_RATE,
)

RESUME_THEN_END = trace(
    "resume-then-end",
    [
        (24, "countdown"),
        (216, "live"),
        (400, "paused"),
        (700, "ended"),
    ],
    end_tick=960,
    rate=ON_RATE,
)

PAUSE_TWICE = trace(
    "pause-twice",
    [
        (24, "countdown"),
        (216, "live"),
        (300, "paused"),
        (700, "live"),
        (760, "paused"),
        (1200, "live"),
        (1500, "ended"),
    ],
    end_tick=1920,
    rate=ON_RATE,
)

TERMINAL_EXIT = trace(
    "terminal-exit",
    [
        (24, "countdown"),
        (216, "live"),
        (900, "ended"),
        (960, "lobby"),
    ],
    end_tick=1200,
    rate=ON_RATE,
)

#: The server was provisioned for 64 Hz and actually delivered 58 Hz. Anchors are derived
#: from 1000/58 so the drift figure is a property of the data, not a typo.
TICK_DRIFT = trace(
    "tick-drift",
    [
        (24, "countdown"),
        (216, "live"),
        (1200, "ended"),
    ],
    end_tick=1920,
    rate=DRIFTED,
)

JITTERY = trace(
    "jittery-frames",
    [
        (12, "countdown"),
        (204, "live"),
        (400, "ended"),
    ],
    end_tick=640,
    rate=jitter_anchors(),
)


CASES: list[dict[str, Any]] = [
    {
        "id": "clean-64hz",
        "title": "A clean 2-minute match on rate",
        "column": "replayed",
        "severity": "clean",
        "summary": "Countdown, one rollback, clean finish. 64 Hz held to the tick.",
        "trace": CLEAN,
    },
    {
        "id": "rollback-storm",
        "title": "Rollback re-simulation overruns its budget",
        "column": "blocking",
        "severity": "major",
        "summary": "finish_resim is allowed 10 ticks; late inputs stretch it to 31.",
        "trace": ROLLBACK_STORM,
    },
    {
        "id": "undeclared-skip",
        "title": "Server ends a match from the countdown",
        "column": "blocking",
        "severity": "critical",
        "summary": "countdown -> ended has no rule anywhere in the table.",
        "trace": UNDECLARED_SKIP,
    },
    {
        "id": "countdown-too-fast",
        "title": "Countdown fires 2.7 s early",
        "column": "blocking",
        "severity": "major",
        "summary": "start_match requires 192 ticks in countdown; it took 6.",
        "trace": COUNTDOWN_TOO_FAST,
    },
    {
        "id": "resume-then-end",
        "title": "Match ends from the paused state",
        "column": "blocking",
        "severity": "critical",
        "summary": "Pausing is legal. Ending the match from paused has no rule at all.",
        "trace": RESUME_THEN_END,
    },
    {
        "id": "pause-twice",
        "title": "pause_match taken twice in one match",
        "column": "blocking",
        "severity": "minor",
        "summary": "The rule is declared once-only, and the trace takes it twice.",
        "trace": PAUSE_TWICE,
    },
    {
        "id": "terminal-exit",
        "title": "Server restarts a finished match",
        "column": "blocking",
        "severity": "critical",
        "summary": "ended is terminal; leaving it should be impossible.",
        "trace": TERMINAL_EXIT,
    },
    {
        "id": "tick-drift",
        "title": "Server delivering 58 Hz against a declared 64 Hz",
        "column": "captured",
        "severity": "major",
        "summary": "Every budget is nominally satisfied while the server runs 9% slow.",
        "trace": TICK_DRIFT,
    },
    {
        "id": "jittery-frames",
        "title": "Mean rate on target, no individual frame is",
        "column": "captured",
        "severity": "minor",
        "summary": "Alternating 50 ms and 75 ms gaps average to a perfect 64 Hz budget.",
        "trace": JITTERY,
    },
]

TABLES = [SKIRMISH_64, SKIRMISH_64_R2, SKIRMISH_BROKEN]


def build() -> dict[str, Any]:
    """Compute every expected result from the engine itself.

    The corpus is emitted as the *authored* documents, but every engine call goes through
    `parse_table` / `parse_trace` first. That is not ceremony: it means the committed fixtures
    were produced through the same boundary a real caller uses, so a parser change shows up
    here instead of in production.
    """
    documents = {table["id"]: table for table in TABLES}
    tables = {name: parse_table(document) for name, document in documents.items()}
    diff = diff_tables(tables["skirmish-64"], tables["skirmish-64-r2"])

    cases = []
    for case in CASES:
        table_name = case["trace"]["tableId"]
        table = tables[table_name]
        trace = parse_trace(case["trace"])
        cases.append(
            {
                **case,
                "table": documents[table_name],
                "expected": {
                    "replay": replay(table, trace),
                    "budgetProfile": budget_profile(table, trace),
                    "tickrate": tickrate_stats(table, trace),
                },
            }
        )

    return {
        "tables": TABLES,
        "cases": cases,
        "tableDiffs": [
            {
                "id": "skirmish-64-vs-r2",
                "title": "skirmish-64 to skirmish-64-r2",
                "before": documents["skirmish-64"],
                "after": documents["skirmish-64-r2"],
                "expected": diff,
            }
        ],
        "tableChecks": [
            {
                "id": table["id"],
                "title": f"Structural check of {table['id']}",
                "table": table,
                "expected": validate_table(tables[table["id"]]),
            }
            for table in TABLES
        ],
    }


def write(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=2, sort_keys=False) + "\n"
    path.write_text(text, encoding="utf8", newline="\n")
    print(f"wrote {path.relative_to(REPO_ROOT)} ({len(text)} bytes)")


def main() -> int:
    payload = build()
    write(DATA / "tables.json", payload["tables"])
    write(DATA / "cases.json", payload["cases"])
    write(DATA / "table-diffs.json", payload["tableDiffs"])
    write(DATA / "table-checks.json", payload["tableChecks"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
