import Link from 'next/link'
import { OPERATIONS, PRODUCT, SHIPPED, OMITTED } from '@/lib/product'
import { CASES, corpusSummary } from '@/lib/corpus'

export const dynamic = 'force-static'

/**
 * What the product is made of, and - just as load-bearing - what it deliberately is not.
 *
 * The omissions are listed with their reason because "no desktop app" reads as an oversight
 * until you say why, and a reader who cannot tell the difference will assume the second.
 */
export default function EnginePage() {
  const summary = corpusSummary()

  return (
    <>
      <section className="lede">
        <p className="lede-what">{PRODUCT.tagline}</p>
        <dl className="lede-figures">
          <div>
            <dt>Operations</dt>
            <dd className="mono">{OPERATIONS.length}</dd>
          </div>
          <div>
            <dt>Shipped surfaces</dt>
            <dd className="mono">{SHIPPED.length}</dd>
          </div>
          <div>
            <dt>Deliberately omitted</dt>
            <dd className="mono">{OMITTED.length}</dd>
          </div>
          <div>
            <dt>Shipped traces</dt>
            <dd className="mono">{summary.cases}</dd>
          </div>
        </dl>
      </section>

      <section aria-labelledby="ops-heading" className="panel">
        <h2 id="ops-heading">The five operations</h2>
        <p className="panel-note">
          Pure functions in Python, invoked as a subprocess over JSON. No clock, no network, no randomness -
          time and any entropy arrive as arguments. They are reachable identically from the CLI, from an MCP
          client, and from this page.
        </p>
        <table className="table">
          <caption className="sr-only">The engine's five operations and the question each answers</caption>
          <thead>
            <tr>
              <th scope="col">Operation</th>
              <th scope="col">Answers</th>
              <th scope="col">Detail</th>
            </tr>
          </thead>
          <tbody>
            {OPERATIONS.map((operation) => (
              <tr key={operation.op}>
                <td className="mono">{operation.op}</td>
                <td>{operation.question}</td>
                <td>{operation.detail}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section aria-labelledby="surfaces-heading" className="panel">
        <h2 id="surfaces-heading">What ships</h2>
        <table className="table">
          <caption className="sr-only">Every capability surface and whether it ships</caption>
          <thead>
            <tr>
              <th scope="col">Surface</th>
              <th scope="col">Status</th>
              <th scope="col">Note</th>
            </tr>
          </thead>
          <tbody>
            {SHIPPED.map((surface) => (
              <tr key={surface.id}>
                <td>{surface.title}</td>
                <td className="mono">shipped</td>
                <td>{surface.summary}</td>
              </tr>
            ))}
            {OMITTED.map((surface) => (
              <tr key={surface.id}>
                <td>{surface.title}</td>
                <td className="mono">omitted</td>
                <td>{surface.reason}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section aria-labelledby="how-heading" className="panel">
        <h2 id="how-heading">How a report reaches this page</h2>
        <p className="panel-note">
          A Vercel function cannot spawn Python, so the browser recomputes the report instead of displaying a
          stored one. That substitution is only honest because it is proven:{' '}
          <code>npm run test --workspace @tickratesim/web</code> replays every shipped trace through the
          TypeScript mirror and through the engine, and fails on the first byte of difference. Where the two
          runtimes disagreed, they did - Python rounds half to even and <code>Math.round</code> does not - and
          the mirror was corrected rather than the test relaxed.
        </p>
        <p className="panel-note">
          Every trace on the board is also reachable as JSON: <Link href="/api/cases">/api/cases</Link>, or
          one case at <Link href="/api/cases/clean-64hz">/api/cases/&lt;id&gt;</Link>.
        </p>
      </section>

      <section aria-labelledby="cases-heading" className="panel">
        <h2 id="cases-heading">The shipped corpus</h2>
        <p className="panel-note">
          Every trace is synthetic but every number is real. The corpus is committed, it is generated by the
          engine, and the Python suite re-derives all of it on every run - so a change to the walk that
          invalidates a documented example fails the build.
        </p>
        <ul className="plain-list">
          {CASES.map((entry) => (
            <li key={entry.id}>
              <Link href={`/cases/${entry.id}`}>{entry.title}</Link> <span className="mono">{entry.id}</span>{' '}
              - {entry.summary}
            </li>
          ))}
        </ul>
      </section>
    </>
  )
}
