import Link from 'next/link'
import { CASES, DIFFS, TABLES } from '@/lib/corpus'

export const dynamic = 'force-static'

/**
 * The tables page.
 *
 * Everything here is the Python engine's own committed output rather than something computed
 * in the browser, because there is no TypeScript mirror of the validator. Saying so on the page
 * is the point: a reader can tell which numbers came from a subprocess they can re-run and
 * which ones the browser derived.
 */
export default function TablesPage() {
  const validated = new Set(CASES.map((entry) => entry.table.id))

  return (
    <>
      <section className="lede">
        <p className="lede-what">
          The declarations every trace on the board was replayed against. Structural findings below are the
          Python engine&apos;s committed output, regenerated by{' '}
          <code>python services/engine/scripts/sync_cases.py</code>.
        </p>
      </section>

      {TABLES.map((table) => (
        <section className="panel" key={table.id} aria-labelledby={`t-${table.id}`}>
          <h2 id={`t-${table.id}`} className="mono">
            {table.id}
          </h2>
          <p className="panel-note">
            {table.tickrateHz} Hz ({Math.round((1000 / table.tickrateHz) * 1000) / 1000} ms per tick), entry{' '}
            <code>{table.entry}</code>, {table.states.length} states, {table.transitions.length} transitions.
            {!validated.has(table.id) && ' Not used by any shipped trace.'}
          </p>

          <table className="table">
            <caption className="sr-only">
              Declared states and transitions of {table.id}, with each tick budget
            </caption>
            <thead>
              <tr>
                <th scope="col">Rule</th>
                <th scope="col">Edge</th>
                <th scope="col">minTicks</th>
                <th scope="col">maxTicks</th>
                <th scope="col">Once-only</th>
              </tr>
            </thead>
            <tbody>
              {table.transitions.map((rule) => (
                <tr key={`${rule.id}-${rule.source}-${rule.target}`}>
                  <td className="mono">{rule.id}</td>
                  <td className="mono">
                    {rule.source} &rarr; {rule.target}
                  </td>
                  <td className="mono num">{rule.minTicks}</td>
                  <td className="mono num">{rule.maxTicks ?? 'unbounded'}</td>
                  <td className="mono">{rule.repeatable ? 'no' : 'yes'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ))}

      {DIFFS.length > 0 && (
        <section className="panel" aria-labelledby="diff-heading">
          <h2 id="diff-heading">Revision</h2>
          <p className="panel-note">
            Two revisions of the same table ship together so the <code>diff_tables</code> question has
            something to answer: which change would make a trace that used to pass start failing?
          </p>
          <ul className="plain-list">
            {DIFFS.map((diff) => (
              <li key={diff.id}>
                <code>{diff.before.id}</code> &rarr; <code>{diff.after.id}</code>
                <Link href="/diff">see the breaking changes</Link>
              </li>
            ))}
          </ul>
        </section>
      )}
    </>
  )
}
